services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/shopify
    depends_on:
      db:
        condition: service_healthy
  db:
    image: library/postgres
    volumes:
      - /var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shopify
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    image: mznurie/shopify-fe
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - db
